// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

type Entry struct {
	Date    string
	Content string
	Keyword interface{}
	Mood    interface{}
	Remarks interface{}
}
